# Generated by Django 3.1.2 on 2021-05-16 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_clamd.validators
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='profile', validators=[django_clamd.validators.validate_file_infection])),
                ('location', django_cryptography.fields.encrypt(models.CharField(max_length=200))),
                ('profession', django_cryptography.fields.encrypt(models.CharField(max_length=200))),
                ('mobile', django_cryptography.fields.encrypt(models.BigIntegerField())),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
