# Generated by Django 3.1.2 on 2021-05-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='branch',
            field=models.CharField(choices=[('ALL', 'ALL'), ('ECE', 'ECE'), ('CSE', 'CSE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('OTHER', 'OTHER')], max_length=10),
        ),
        migrations.AlterField(
            model_name='resource',
            name='year',
            field=models.CharField(choices=[('ANY', 'ANY'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=5),
        ),
    ]
