# Generated by Django 3.1.2 on 2021-05-16 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_resource_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='addedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
