# Generated by Django 3.1.2 on 2021-05-16 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config',
        ),
    ]
