# Generated by Django 3.1.2 on 2021-05-16 06:34

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_delete_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
                ('email', django_cryptography.fields.encrypt(models.EmailField(max_length=254))),
                ('phone', django_cryptography.fields.encrypt(models.BigIntegerField())),
                ('message', django_cryptography.fields.encrypt(models.CharField(max_length=2048))),
            ],
        ),
        migrations.CreateModel(
            name='SiteAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=2048)),
                ('link_exist', models.BooleanField()),
                ('link', models.CharField(blank=True, max_length=2048, null=True)),
            ],
        ),
    ]
